
# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: docker:latest


# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - build

build:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: build
  script:
    - echo $password | docker login --username $username --password-stdin
    - docker build -t shobu13/kindly-kappa-server server/
    - docker tag shobu13/kindly-kappa-server shobu13/kindly-kappa-server:latest
    - docker push shobu13/kindly-kappa-server
    - docker build -t shobu13/kindly-kappa-frontend frontend/
    - docker tag shobu13/kindly-kappa-frontend shobu13/kindly-kappa-frontend:latest
    - docker push shobu13/kindly-kappa-frontend
